[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.rust]

[workspace.lints.clippy]

[workspace.dependencies]
agent = { path = "crates/agent" }
tools = { path = "crates/tools" }

anyhow = "1"
async-channel = "2"
gpui = { package = "gpui-pre", version = "0.3.5" }
# https://github.com/longbridge/gpui-kit/pull/3136
gpui-base = { git = "https://github.com/tidely/gpui-kit", branch = "selected-source-range" }
gpui_platform = { package = "gpui-pre-platform", version = "0.3.5", features = ["font-kit", "wayland", "x11", "runtime_shaders"] }
futures = "0.3"
iroh = "1.2.0"
itertools = "0.14"
markdown = "1.0.0"
postcard = { version = "1.1.3", features = ["use-std"] }
rig = { git = "https://github.com/0xPlaygrounds/rig", rev = "2d16c1b25f6749b3a2cd841beddf767106495069" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
syntect = { version = "5.2", default-features = false, features = ["default-fancy"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
tokio-util = { version = "0.7", features = ["codec"] }
uuid = { version = "1", features = ["v4"] }
